var data = {
    "message":"accurate",
    "cod":"200",
    "count":15,
    "list":[
        {
            "id":495260,
            "name":"Shcherbinka",
            "coord":{
                "lon":37.559719,
                "lat":55.499722
            },
            "main":{
                "temp":299.24,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":300.55
            },
            "dt":1466185001,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":8
            },
            "weather": [
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"02d"
                }
            ]
        },
        {
            "id":564517,
            "name":"Dubrovitsy",
            "coord":{
                "lon":37.486698,
                "lat":55.43969
            },
            "main":{
                "temp":299.24,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":300.55
            },
            "dt":1466185242,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":0
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"01d"
                }
            ]
        },
        {
            "id":570578,
            "name":"Butovo",
            "coord":{
                "lon":37.57972,
                "lat":55.548328
            },
            "main":{
                "temp":298.74,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":299.26
            },
            "dt":1466185081,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":8
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"02d"
                }
            ]
        },
        {
            "id":545782,
            "name":"Kommunarka",
            "coord":{
                "lon":37.489319,
                "lat":55.569519
            },
            "main":{
                "temp":298.72,
                "humidity":58,
                "pressure":1014,
                "temp_min":298.15,
                "temp_max":299.26
            },
            "dt":1466185001,
            "wind":{
                "speed":2.35,
                "deg":163.502
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":0
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"01d"
                }
            ]
        },
        {
            "id":6417490,
            "name":"Lesparkkhoz",
            "coord":{
                "lon":37.601391,
                "lat":55.54306
            },
            "main":{
                "temp":299.23,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":300.55
            },
            "dt":1466185242,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":8
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"02d"
                }
            ]
        },
        {
            "id":526736,
            "name":"Sed’moy Mikrorayon",
            "coord":{
                "lon":37.57972,
                "lat":55.562222
            },
            "main":{
                "temp":298.74,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":299.26
            },
            "dt":1466185081,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":8
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"02d"
                }
            ]
        },
        {
            "id":473051,
            "name":"Vlas’yevo",
            "coord":{
                "lon":37.379444,
                "lat":55.460278
            },
            "main":{
                "temp":298.75,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":299.26
            },
            "dt":1466185081,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":0
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"01d"
                }
            ]
        },
        {
            "id":578680,
            "name":"Bachurino",
            "coord":{
                "lon":37.52,
                "lat":55.580002
            },
            "main":{
                "temp":298.74,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":299.26
            },
            "dt":1466185081,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":8
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"02d"
                }
            ]
        },
        {
            "id":554629,
            "name":"Shestoy Mikrorayon",
            "coord":{
                "lon":37.583328,
                "lat":55.566669
            },
            "main":{
                "temp":299.42,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":300.75
            },
            "dt":1466184828,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":8
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"02d"
                }
            ]
        },
        {
            "id":508101,
            "name":"Podolsk",
            "coord":{
                "lon":37.554722,
                "lat":55.424179
            },
            "main":{
                "temp":299.29,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":300.55
            },
            "dt":1466185242,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":0
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"01d"
                }
            ]
        },
        {
            "id":6417039,
            "name":"Shchipchinki",
            "coord":{
                "lon":37.537102,
                "lat":55.419571
            },
            "main":{
                "temp":298.74,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":299.26
            },
            "dt":1466185001,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":0
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"01d"
                }
            ]
        },
        {
            "id":819743,
            "name":"Staraya Bitsa",
            "coord":{
                "lon":37.569168,
                "lat":55.576668
            },
            "main":{
                "temp":298.74,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":299.26
            },
            "dt":1466185081,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":8
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"02d"
                }
            ]
        },
        {
            "id":576221,
            "name":"Bittsa",
            "coord":{
                "lon":37.575001,
                "lat":55.576389
            },
            "main":{
                "temp":299.22,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":300.55
            },
            "dt":1466185242,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":8
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"02d"
                }
            ]
        },
        {
            "id":478323,
            "name":"Uslon’",
            "coord":{
                "lon":37.641392,
                "lat":55.465
            },
            "main":{
                "temp":298.75,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":299.26
            },
            "dt":1466185081,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":0
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"01d"
                }
            ]
        },
        {
            "id":6417277,
            "name":"Piskovo",
            "coord":{
                "lon":37.360279,
                "lat":55.538612
            },
            "main":{
                "temp":299.23,
                "humidity":57,
                "pressure":1016,
                "temp_min":298.15,
                "temp_max":300.55
            },
            "dt":1466185242,
            "wind":{
                "speed":2.06,
                "gust":2.06,
                "deg":180
            },
            "sys":{
                "country":""
            },
            "clouds":{
                "all":0
            },
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"Sky is Clear",
                    "icon":"01d"
                }
            ]
        }
    ]
};

module.exports = data;